# Generated by Django 5.2.9 on 2025-12-06 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма для выплат')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='ISO 4217 Код валюты')),
                ('recipient_account', models.CharField(max_length=100, verbose_name='Кошелек получателя')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус выплаты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
